char inttochar(int i);
int ktngaythang(int a[][3], int dem);
void chuyenthuong(char a[]);
void ngayhet(int a[][3], int dem, int b[][3]);
int timID(char ten_ID[][9], char ID[], int dem);
void xoa_ten(char a[][40], int i, int dem);
void xoa_tenID(char a[][9], int i, int dem);
void xoa_tendc(char a[][200], int i, int dem);
void xoa_tenns(int a[][3], int i, int dem);
void xoa_tengt(int a[], int i, int dem);
void rutchuoi(char a[]);
int timten(char ten[][40], char a[], int dem, int &i);
void viethoa(char a[]);
void chuanhoa(char a[]);
void congngay(int a[][3], int b[][3], int demt);
int ktnamnhuan(int a);
int trungay(int a[][3], int b[][3], int m, int n);
int demngay(int a[][3], int demtt);
void xoa(char a[][40], int &n);
int cmnd(char a[][40], int dem, char ID[]);